
CXXFLAGS = -std=c++98 -pedantic -Wall -Werror
#CXXFLAGS = -std=c++11 -pedantic -Wall -Werror
#CXXFLAGS = -std=c++14 -pedantic -Wall -Werror

default: build
clean:
	rm -f *~
	rm -f base-derived-virtual-destructor
	rm -f base-derived-virtual-method
	rm -f member-variable-initialisation-order
	rm -f proggy

build-base-derived-virtual-destructor: base-derived-virtual-destructor
build-base-derived-virtual-method: base-derived-virtual-method
build-member-variable-initialisation-order: member-variable-initialisation-order
build-proggy: proggy

run-base-derived-virtual-method: base-derived-virtual-method
	./base-derived-virtual-method


